---
# This playbook setup all necessary software

- hosts: docker-registry
  user: "{{user_name}}"
  sudo: yes

  roles:
    - nginx-build
    - docker-compose-build

  vars_files:
    - group_vars/common.yml