---

- include: ../../docker-compose-wipe/tasks/main.yml

- name: Add GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- name: Add stable Docker repository
  apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
      update_cache: yes

- name: Install latest Docker CE
  apt: pkg=docker-ce state=present update_cache=yes

- name: Checking dokcer version
  command: docker --version
  register: docker_version

- debug: msg={{docker_version.stdout}}

- name: Checking docker compose version
  command: docker-compose --version
  register: docker_compose_version

- debug: msg={{docker_compose_version.stdout}}