---

- name: Delete existing docker-compose version if it's different.
  file: path={{docker_compose_dir} state=absent
  when: docker_compose_current_version.stdout is defined 
        and docker_compose_version not in docker_compose_current_version.stdout
