---

- name: Checking if nginx exists
  stat: 
  register: nginxpresent

- name: Stopping nginx
  service: name=nginx state=stopped
  when: nginxpresent.stat.exists is defined and nginxpresent.stat.exists == True
  sudo: yes