---

- include: ../../nginx-stop/tasks/main.yml

- name: stop and disable nginx
  service: name=nginx state=stopped enabled=no
  sudo: yes
  when: nginxpresent.stat.exists is defined and nginxpresent.stat.exists == True

- name: Removing nginx init script
  file: path=/etc/init.d/nginx state=absent
  sudo: yes

- name: Wipe nginx root directory
  file: path={{nginx_home}} state=absent
  sudo: yes